services:

  api-gateway:
    container_name: api-gateway
    image: node:20-bookworm
    working_dir: /usr/src/app
    volumes:
      - ./api-gateway:/usr/src/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - JWT_SECRET=secret
      - JWT_EXPIRES_IN=1d
    depends_on:
      - rabbitmq
    stdin_open: true
    tty: true

  users-services:
    container_name: users-service
    image: node:20-bookworm
    working_dir: /usr/src/app
    volumes:
      - ./users-services:/usr/src/app
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=users
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      - postgres
      - rabbitmq
    stdin_open: true
    tty: true

  transactions-services:
    container_name: transactions-service
    image: node:20-bookworm
    working_dir: /usr/src/app
    volumes:
      - ./transactions-services:/usr/src/app
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=transactions
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      - postgres
      - rabbitmq
    stdin_open: true
    tty: true

  goals-services:
    container_name: goals-service
    image: node:20-bookworm
    working_dir: /usr/src/app
    volumes:
      - ./goals-services:/usr/src/app
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=goals
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      - postgres
      - rabbitmq
    stdin_open: true
    tty: true

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./init_pg:/docker-entrypoint-initdb.d

  rabbitmq:
    container_name: rebbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"  # Web UI для RabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest



