services:

  front-end:
    container_name: front-end
    image: node:20-bookworm
    working_dir: /usr/src/app
    volumes:
      - ./front-end:/usr/src/app
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - PORT=4000
      - API_GATEWAY_PORT=3000
    depends_on:
      - api-gateway
    stdin_open: true
    tty: true
    command: sh -c "cd react-app && npm run start"

  api-gateway:
    container_name: api-gateway
    image: node:20-bookworm
    working_dir: /usr/src/app
    volumes:
      - ./api-gateway:/usr/src/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - JWT_SECRET=secret
      - JWT_EXPIRES_IN=1d
    depends_on:
      - rabbitmq
    stdin_open: true
    tty: true
    command: sh -c "cd nest-app && npm run start"

  users-services:
    container_name: users-service
    image: node:20-bookworm
    working_dir: /usr/src/app
    volumes:
      - ./users-services:/usr/src/app
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=users
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - DOCKER_HOST=unix:///var/run/docker.sock
      - TESTCONTAINERS_RYUK_DISABLED=true
    depends_on:
      - postgres
      - rabbitmq
    stdin_open: true
    tty: true
    command: sh -c "cd nest-app && npm run start"

  transactions-services:
    container_name: transactions-service
    image: node:20-bookworm
    working_dir: /usr/src/app
    volumes:
      - ./transactions-services:/usr/src/app
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=transactions
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      - postgres
      - rabbitmq
    stdin_open: true
    tty: true
    command: sh -c "cd nest-app && npm run start"

  goals-services:
    container_name: goals-service
    image: node:20-bookworm
    working_dir: /usr/src/app
    volumes:
      - ./goals-services:/usr/src/app
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=goals
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      - postgres
      - rabbitmq
    stdin_open: true
    tty: true
    command: sh -c "cd nest-app && npm run start"

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./init_pg:/docker-entrypoint-initdb.d

  rabbitmq:
    container_name: rebbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"  # Web UI для RabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest



