export const transactionCategories = [
    "car", 
    "charity", 
    "budget and taxes", 
    "cash", 
    "money transfers", 
    "investments", 
    "other", 
    "stationery", 
    "cafes and restaurants", 
    "flowers", 
    "cinema", 
    "books", 
    "utilities", 
    "beauty", 
    "health", 
    "courier services", 
    "clothing and footwear", 
    "household appliances", 
    "loan repayment", 
    "travel", 
    "mobile top-up", 
    "subscriptions", 
    "groceries", 
    "advertising services", 
    "repairs", 
    "entertainment and sports", 
    "insurance", 
    "taxi", 
    "pets", 
    "fines", 
    "jewelry"
];